---

- hosts: all
  become: true
  pre_tasks:

  - name: Installation of Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu_controller_node
  become: true
  roles:
    - Neutron
    - Horizon
    - Cinder
